mail:
  debug: true
recaptcha:
  secret: 6LcHNj8jAAAAAInWR8B5VFE_7LcLIxGfakcaEu3i
spring:
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
  application:
    name: twitter-clone
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
  mail:
    host: smtp.gmail.com
    protocol: smtp
    username: temptwitterclone@gmail.com
    password: chruasrycdlkqjbo
    port: 587
    properties:
      mail:
        smtp:
           auth: true
           starttls:
            enable: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      #ddl-auto: create
    generate-ddl: false
    #generate-ddl: true

  kafka:
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-empty-json-arrays: false

  datasource:
    url: jdbc:postgresql://localhost:5442/testdb
    username: user
    password: password
    driverClassName: org.postgresql.Driver

  sql:
    init:
      platform: postgres
      
  freemarker:
      expose-request-attributes: true

twitter-clone:
  upload-path: /Users/borisstarodubtsev/IdeaProjects/twitter-clone/upload
  kafka:
      consumer:
        groupId: "someGroupId"
        topic: "threats"
      producer:
        topic: "threats"
        createdEventType: ThreatsFound
        source: twitter-clone

management:
  endpoint:
    loggers.enabled: true
    prometheus.enabled: true
    metrics.enabled: true
  health:
    defaults:
      enabled: false
  endpoints.web:
    base-path: /actuator
    exposure.include: health,info,prometheus,loggers
  metrics.export.prometheus.enabled: true


blacklist:
  threats:
    - name: war
      level: WARNING
      tags:
        - war
        - weapon
        - soldier
        - tank
        - warplane
    - name:  politic
      level: DANGER
      tags:
        - government
        - parties
        - trump
        - history
    - name: crime
      level: CRITICAL
      tags:
        - cosanostra
        - gangster
        - mafia
        - drugs

