openapi: 3.0.0
info:
  title: Example open api file
  version: '1.0'
  description: 'Open API main'
servers:
  - url: 'http://localhost:8080/'
    description: Test
paths:
  /apigen-getusers:
    parameters: []
    get:
      summary: get users example
      operationId: getUsers
      description: get amount of users with required active parameter
      parameters:
        - name: active
          in : query
          required: false
          schema:
            type: boolean
        - name: amount
          in : query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponseDto'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

components:
  schemas:
    UserResponseDto:
      title: UserResponseDto
      type: object
      description: User response object
      properties:
        id:
          type: string
          description: For API purposes only
        username:
          type: string
          description: Name of user
        active:
          type: boolean
          description: Is user active
        email:
          type: string
          description: Email
